### ISSUE TITLE
It should be more prominent that a user should settle a gray unsettled course

### ISSUE THREAD

**Issue by churichard** [TigerAppsOrg/TigerPath#93] opened 2018-05-14 16:17 UTC
Could potentially do this by putting a red (!) icon on the gray course, and then when the user hovers over the course, showing a tooltip informing them that this course should be settled underneath some requirement. We could also just have the tooltip and skip the red icon.

**Comment by bnehoran** [comment] 2018-05-16 01:58
Something like this?
![image](https://user-images.githubusercontent.com/9757500/40092320-c8a7eb9a-588a-11e8-837a-bc3f148ff55a.png)
(note: I haven't actually implemented anything. Just a mockup to test how it might look.)

The problem is that it might make it seem to the user as if they've done something wrong, when in fact they haven't. They just haven't completed what they're supposed to do to get the course to count.

**Comment by bnehoran** [comment] 2018-05-16 02:17
Maybe it would be good to show some message the first time they add a course that can be counted for more than one requirement.

Something to the extent of
`This course could count for only one of the requirements shown on the right. Select one of them by clicking on the corresponding grayed-out course card. This assigns the class to that requirement. You can always to click again to undo the assignment.`

**Comment by bnehoran** [comment] 2018-09-13 05:28
Mostly addressed by #151

**Closed as completed by bnehoran** 2018-09-13 05:28 UTC
Labels: UI
